# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 62e460bc73f3dda711bf782e484d09545ce2f13d20a47ebbc940575120d9ab7df9e85ce3a36fb97937e2e3ad5cc677605924264189843c8be6f071b397dfd15c

test:
  secret_key_base: 59dad93395a09bb497d976acdd8e7dd59bb79fdd0a41a2cecd99c53e24f6b526f7be311c718168b4e91c965969ff49d38dfbd76acc0d45ba3cdf0c8c680d8fff

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
